application: gae-service-samples
service: cloud-endpoints-framework
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /_ah/api/.*
  script: main.api

libraries:
- name: pycrypto
  version: 2.6
- name: ssl
  version: 2.7.11

env_variables:
    ENDPOINTS_SERVICE_NAME: samples.endpoints.cloud-endpoints-framework-dot-gae-service-samples.appspot.com
    ENDPOINTS_SERVICE_VERSION: 2017-05-13r1
